-- The below command defines the schema where all the indexes are created
SET search_path TO public;

-- -----------
-- ADMISSIONS
-- -----------

CREATE INDEX ADMISSIONS_INDX02 ON ADMISSIONS (SUBJECT_ID);
CREATE INDEX ADMISSIONS_INDX03 ON ADMISSIONS (ADMISSION_TYPE);

-- ---------
-- CALLOUT--
-- ---------

CREATE INDEX CALLOUT_INDX02 ON CALLOUT (SUBJECT_ID);
CREATE INDEX CALLOUT_INDX03 ON CALLOUT (HADM_ID);
CREATE INDEX CALLOUT_INDX04 ON CALLOUT (CURR_CAREUNIT);
CREATE INDEX CALLOUT_INDX05 ON CALLOUT (CALLOUT_SERVICE);

CREATE INDEX ON CPTEVENTS (SUBJECT_ID);
CREATE INDEX ON CPTEVENTS (HADM_ID);
CREATE INDEX ON CPTEVENTS (CPT_CD);

-- -------------
-- CHARTEVENTS
-- -------------
CREATE INDEX ON CHARTEVENTS (SUBJECT_ID);
CREATE INDEX ON CHARTEVENTS (HADM_ID);
CREATE INDEX ON CHARTEVENTS (ICUSTAY_ID);
CREATE INDEX ON CHARTEVENTS (ITEMID);
CREATE INDEX ON CHARTEVENTS (CGID);

-- ---------
-- D_CPT
-- ---------

CREATE INDEX ON D_CPT (CATEGORY);
      
-- ------------------
-- D_ICD_DIAGNOSES
-- ------------------

CREATE INDEX ON D_ICD_DIAGNOSES (SHORT_TITLE);

-- ------------------
-- D_ICD_PROCEDURES
-- ------------------

CREATE INDEX ON D_ICD_PROCEDURES (SHORT_TITLE);

-- ---------
-- D_ITEMS
-- ---------

CREATE INDEX ON D_ITEMS (CATEGORY);

-- -------------
-- D_LABITEMS
-- -------------

CREATE INDEX ON D_LABITEMS (LOINC_CODE);

-- -----------------
-- DATETIMEEVENTS
-- -----------------

CREATE INDEX ON DATETIMEEVENTS (SUBJECT_ID);
CREATE INDEX ON DATETIMEEVENTS (HADM_ID);
CREATE INDEX ON DATETIMEEVENTS (ICUSTAY_ID);
CREATE INDEX ON DATETIMEEVENTS (ITEMID);
CREATE INDEX ON DATETIMEEVENTS (CGID);
CREATE INDEX ON DATETIMEEVENTS (CHARTTIME);
CREATE INDEX ON DATETIMEEVENTS (VALUE);

-- ----------------
-- DIAGNOSES_ICD
-- ----------------

CREATE INDEX ON DIAGNOSES_ICD (SUBJECT_ID);
CREATE INDEX ON DIAGNOSES_ICD (HADM_ID);
CREATE INDEX ON DIAGNOSES_ICD (ICD9_CODE);

-- ------------
-- DRGCODES
-- ------------

CREATE INDEX ON DRGCODES (SUBJECT_ID);
CREATE INDEX ON DRGCODES (HADM_ID);
CREATE INDEX ON DRGCODES (DRG_TYPE);
CREATE INDEX ON DRGCODES (DRG_CODE);

-- ----------------
-- ICUSTAYS
-- ----------------

CREATE INDEX ON ICUSTAYS (SUBJECT_ID);
CREATE INDEX ON ICUSTAYS (HADM_ID);
CREATE INDEX ON ICUSTAYS (FIRST_CAREUNIT);
CREATE INDEX ON ICUSTAYS (LAST_CAREUNIT);
      
-- --------------
-- INPUTEVENTS_CV
-- --------------

CREATE INDEX ON INPUTEVENTS_CV (SUBJECT_ID);
CREATE INDEX ON INPUTEVENTS_CV (HADM_ID);
CREATE INDEX ON INPUTEVENTS_CV (ICUSTAY_ID);
CREATE INDEX ON INPUTEVENTS_CV (ITEMID);
CREATE INDEX ON INPUTEVENTS_CV (CGID);
CREATE INDEX ON INPUTEVENTS_CV (ORDERID);

-- --------------
-- INPUTEVENTS_MV
-- --------------

CREATE INDEX ON INPUTEVENTS_MV (SUBJECT_ID);
CREATE INDEX ON INPUTEVENTS_MV (HADM_ID);
CREATE INDEX ON INPUTEVENTS_MV (ICUSTAY_ID);
CREATE INDEX ON INPUTEVENTS_MV (ITEMID);
CREATE INDEX ON INPUTEVENTS_MV (CGID);
CREATE INDEX ON INPUTEVENTS_MV (STARTTIME);
CREATE INDEX ON INPUTEVENTS_MV (ENDTIME);
CREATE INDEX ON INPUTEVENTS_MV (ORDERID);

-- ------------
-- LABEVENTS
-- ------------

CREATE INDEX ON LABEVENTS (SUBJECT_ID);
CREATE INDEX ON LABEVENTS (HADM_ID);
CREATE INDEX ON LABEVENTS (ITEMID);
CREATE INDEX ON LABEVENTS (CHARTTIME);
      
-- --------------------
-- MICROBIOLOGYEVENTS
-- --------------------

CREATE INDEX ON MICROBIOLOGYEVENTS (SUBJECT_ID);
CREATE INDEX ON MICROBIOLOGYEVENTS (HADM_ID);
CREATE INDEX ON MICROBIOLOGYEVENTS (CHARTDATE);
CREATE INDEX ON MICROBIOLOGYEVENTS (SPEC_ITEMID);
CREATE INDEX ON MICROBIOLOGYEVENTS (SPEC_TYPE_DESC);
CREATE INDEX ON MICROBIOLOGYEVENTS (ORG_ITEMID);
CREATE INDEX ON MICROBIOLOGYEVENTS (ORG_NAME);
CREATE INDEX ON MICROBIOLOGYEVENTS (AB_ITEMID);
CREATE INDEX ON MICROBIOLOGYEVENTS (AB_NAME);

-- -------------
-- NOTEEVENTS
-- -------------

CREATE INDEX ON NOTEEVENTS (SUBJECT_ID);
CREATE INDEX ON NOTEEVENTS (HADM_ID);
CREATE INDEX ON NOTEEVENTS (CHARTDATE);
CREATE INDEX ON NOTEEVENTS (CATEGORY);
CREATE INDEX ON NOTEEVENTS (CGID);
CREATE INDEX ON NOTEEVENTS (DESCRIPTION);

-- --------------
-- OUTPUTEVENTS
-- --------------

CREATE INDEX ON OUTPUTEVENTS (SUBJECT_ID);
CREATE INDEX ON OUTPUTEVENTS (HADM_ID);
CREATE INDEX ON OUTPUTEVENTS (ICUSTAY_ID);
CREATE INDEX ON OUTPUTEVENTS (ITEMID);
CREATE INDEX ON OUTPUTEVENTS (CGID);
CREATE INDEX ON OUTPUTEVENTS (CHARTTIME);

-- -----------
-- PATIENTS
-- -----------

CREATE INDEX ON PATIENTS (EXPIRE_FLAG);

-- ----------------
-- PRESCRIPTIONS
-- ----------------

CREATE INDEX ON PRESCRIPTIONS (SUBJECT_ID);
CREATE INDEX ON PRESCRIPTIONS (HADM_ID);
CREATE INDEX ON PRESCRIPTIONS (ICUSTAY_ID);
CREATE INDEX ON PRESCRIPTIONS (DRUG_TYPE);
CREATE INDEX ON PRESCRIPTIONS (DRUG);

-- -----------------
-- PROCEDURES_MV
-- -----------------

CREATE INDEX ON PROCEDUREEVENTS_MV (SUBJECT_ID);
CREATE INDEX ON PROCEDUREEVENTS_MV (HADM_ID);
CREATE INDEX ON PROCEDUREEVENTS_MV (ICUSTAY_ID);
CREATE INDEX ON PROCEDUREEVENTS_MV (ITEMID);
CREATE INDEX ON PROCEDUREEVENTS_MV (CGID);
CREATE INDEX ON PROCEDUREEVENTS_MV (ORDERCATEGORYNAME);
      
-- -----------------
-- PROCEDURES_ICD
-- -----------------

CREATE INDEX ON PROCEDURES_ICD (SUBJECT_ID);
CREATE INDEX ON PROCEDURES_ICD (HADM_ID);
CREATE INDEX ON PROCEDURES_ICD (ICD9_CODE);

-- -----------
-- SERVICES
-- -----------

CREATE INDEX ON SERVICES (SUBJECT_ID);
CREATE INDEX ON SERVICES (HADM_ID);
CREATE INDEX ON SERVICES (PREV_SERVICE);
CREATE INDEX ON SERVICES (CURR_SERVICE);

-- -----------
-- TRANSFERS
-- -----------

CREATE INDEX ON TRANSFERS (SUBJECT_ID);
CREATE INDEX ON TRANSFERS (HADM_ID);
CREATE INDEX ON TRANSFERS (ICUSTAY_ID);
CREATE INDEX ON TRANSFERS (PREV_CAREUNIT);
CREATE INDEX ON TRANSFERS (CURR_CAREUNIT);
CREATE INDEX ON TRANSFERS (LOS);
